services:
  database:
    image: postgres:16-alpine
    container_name: pg-practica1
    restart: unless-stopped
    environment:
      POSTGRES_DB: practica1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: practica1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d practica1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    name: practica1_pgdata
